# Site settings
baseurl = "https://faqs.gmt-china.org/"
languageCode = "zh-CN"
title = "GMT FAQs"
theme = "hugo-faq-theme"

# Do not build files for websites.
disableKinds = ["RSS", "sitemap", "404"]

[params]
	# Custom styling
	# To customize the styling of this theme, uncomment and edit the following line to point
	# to your site's css in the assets/ directory.

	custom_css = ["css/GMT_FAQs.css"]
